/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서버 상태 확인 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 새 볼트 생성 */
        post: operations["createVault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/raw/{filePath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raw 마크다운 조회 */
        get: operations["getRawFile"];
        /** Raw 마크다운 업로드 (SHA-256 자동 계산) */
        put: operations["uploadRawFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** JSON 메타데이터로 파일 업로드 */
        put: operations["uploadFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/file/{filePath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 파일 내용 조회 */
        get: operations["getFile"];
        put?: never;
        post?: never;
        /** 파일 소프트 삭제 */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 파일 목록 조회 */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/versions/{filePath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 파일 버전 목록 조회 */
        get: operations["listVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 파일 내용 편집 (old_text → new_text 교체) */
        post: operations["editFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 폴더 트리 구조 조회 */
        get: operations["listFolder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 마크다운 파일 검색 */
        get: operations["searchFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 동기화 이벤트 폴링 */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 디바이스 동기화 상태 업데이트 */
        put: operations["updateSyncStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 볼트 전체 마크다운 내보내기 */
        get: operations["exportVault"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/attachment/{filePath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 바이너리 첨부파일 조회 */
        get: operations["getAttachment"];
        /** 바이너리 첨부파일 업로드 (MinIO) */
        put: operations["uploadAttachment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 미해결 충돌 목록 조회 */
        get: operations["listConflicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/conflicts/{conflict_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 충돌 해결 (accept/reject) */
        post: operations["resolveConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/conflicts/{conflict_id}/merge-resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 수동 3-way merge 해결 */
        post: operations["mergeResolveConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 볼트 디바이스 목록 조회 */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 디바이스 제거 */
        delete: operations["removeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 배치 연산 실행 */
        post: operations["batchOperations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vault/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 파일 이동/이름 변경 */
        post: operations["moveFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/sync/{vault_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 실시간 동기화 WebSocket
         * @description WebSocket 연결. OpenAPI 3.0은 WebSocket을 네이티브로 지원하지 않으므로
         *     참조용으로만 문서화합니다.
         *
         *     클라이언트 메시지: { "type": "ping" }
         *     서버 메시지: WSMessage 스키마 참조
         */
        get: operations["wsSync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                /** @example name is required */
                message: string;
                /** @example 400 */
                statusCode: number;
            };
        };
        VaultCreateRequest: {
            name: string;
        };
        VaultResponse: {
            /** Format: uuid */
            vault_id: string;
            api_key: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        UploadResult: {
            /** Format: uuid */
            id: string;
            path: string;
            /** @description SHA-256 해시 */
            hash: string;
            size_bytes: number | null;
            version: number;
            /** @description 3-way merge 자동 병합 여부 */
            auto_merged?: boolean;
            /**
             * @description 병합 타입 (auto = 자동 병합)
             * @enum {string}
             */
            merge_type?: "auto" | "normal";
            /** @description REQ-SYNC-004: rename 리다이렉트 시 원본 경로 */
            redirected_from?: string;
        };
        FileInfo: {
            /** Format: uuid */
            id: string;
            path: string;
            hash: string;
            size_bytes: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FileDetail: {
            /** Format: uuid */
            id: string;
            path: string;
            hash: string;
            size_bytes: number | null;
            content: string | null;
            /** @enum {string} */
            file_type?: "markdown" | "attachment";
            version: number;
        };
        FileUploadRequest: {
            path: string;
            content?: string;
            /** @description SHA-256 해시 */
            hash: string;
            /** @description 충돌 감지용 클라이언트 해시 */
            base_hash?: string;
        };
        DeleteResponse: {
            /** @example File deleted */
            message: string;
            deleted: boolean;
            path: string;
        };
        EditRequest: {
            path: string;
            old_text: string;
            new_text: string;
        };
        EditResponse: {
            /** Format: uuid */
            id: string;
            path: string;
            version: number;
            hash: string;
            /** @description 교체 발생 횟수 */
            changes: number;
        };
        FolderEntry: {
            name: string;
            path: string;
            /** @enum {string} */
            type: "file" | "folder";
            hash?: string;
            size_bytes?: number | null;
            /** Format: date-time */
            updated_at?: string;
        };
        FolderListResponse: {
            folder: string;
            entries: components["schemas"]["FolderEntry"][];
        };
        FileVersion: {
            version_num: number;
            content_hash: string;
            storage_key: string;
            /** Format: date-time */
            created_at: string;
        };
        VersionListResponse: {
            versions: components["schemas"]["FileVersion"][];
        };
        BaseContentResponse: {
            content: string;
            hash: string;
        };
        SearchResultItem: {
            path: string;
            snippet: string;
            score: number;
        };
        SearchResponse: {
            results: components["schemas"]["SearchResultItem"][];
            total: number;
        };
        SyncEvent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            event_type: "created" | "updated" | "deleted" | "moved";
            file_path: string | null;
            file_type?: string | null;
            device_id: string;
            sequence?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        EventsResponse: {
            events: components["schemas"]["SyncEvent"][];
        };
        SyncStatusRequest: {
            device_id: string;
            /** Format: uuid */
            last_event_id: string;
        };
        SyncStatusResponse: {
            device_id: string;
            /** Format: uuid */
            vault_id: string;
            /** Format: uuid */
            last_event_id: string;
            /** Format: date-time */
            last_sync_at: string;
        };
        DiffOperation: {
            /** @description 0=equal, 1=insert, -1=delete */
            op: number;
            text: string;
        };
        ConflictResult: {
            /** @enum {boolean} */
            conflict: true;
            current_hash: string;
            incoming_hash: string;
            conflict_path: string;
            /** @description 서버 충돌 레코드 ID (resolve API 호출용) */
            conflict_id?: string;
            base_hash?: string;
            diff?: components["schemas"]["DiffOperation"][];
            can_auto_merge?: boolean;
        };
        ConflictInfo: {
            /** Format: uuid */
            id: string;
            original_path?: string | null;
            conflict_path: string;
            /** Format: date-time */
            created_at: string;
        };
        ConflictListResponse: {
            conflicts: components["schemas"]["ConflictInfo"][];
        };
        ConflictResolveRequest: {
            /** @enum {string} */
            resolution: "accept" | "reject";
        };
        ConflictResolveResponse: {
            resolution: string;
            /** Format: uuid */
            conflict_id: string;
            /** Format: date-time */
            resolved_at: string;
        };
        MergeResolveRequest: {
            content: string;
            /** @description SHA-256 해시 */
            hash: string;
        };
        MergeResolveResponse: {
            /** Format: date-time */
            resolved_at: string;
        };
        DeviceInfo: {
            device_id: string;
            /** Format: uuid */
            vault_id: string;
            last_event_id: string | null;
            /** Format: date-time */
            last_sync_at: string | null;
        };
        DeviceListResponse: {
            devices: components["schemas"]["DeviceInfo"][];
        };
        BatchOperation: {
            /** @enum {string} */
            type: "create" | "delete";
            data: {
                path: string;
                content?: string;
                hash?: string;
            };
        };
        BatchRequest: {
            operations: components["schemas"]["BatchOperation"][];
        };
        BatchResultItem: {
            status: number;
            /** @description 성공 시 UploadResult 또는 DeleteResponse */
            data?: unknown;
            error?: string;
        };
        BatchResponse: {
            results: components["schemas"]["BatchResultItem"][];
        };
        MoveRequest: {
            from: string;
            to: string;
        };
        MoveResponse: {
            path: string;
            /** Format: uuid */
            id: string;
        };
        ExportFile: {
            path: string;
            content: string;
            hash: string;
            version: number;
            /** Format: date-time */
            updated_at: string;
        };
        ExportResponse: {
            files: components["schemas"]["ExportFile"][];
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            database: boolean;
            storage: boolean;
            websocket: boolean;
            /** Format: date-time */
            timestamp: string;
        };
        WSSyncEventData: {
            id?: string;
            event_type?: string;
            file_path?: string;
            file_type?: string;
            device_id?: string;
            created_at?: string;
            sequence?: number;
        };
        WSMessage: {
            /** @enum {string} */
            type?: "connected" | "sync_event" | "pong";
            vault_id?: string;
            timestamp?: string;
            data?: components["schemas"]["WSSyncEventData"];
        };
    };
    responses: never;
    parameters: {
        /** @description 볼트 UUID */
        VaultId: string;
        /** @description 파일 경로 (와일드카드) */
        FilePath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 서버 상태 정보 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    createVault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VaultCreateRequest"];
            };
        };
        responses: {
            /** @description 볼트 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaultResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getRawFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                /** @description 파일 경로 (와일드카드) */
                filePath: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 파일 내용 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            /** @description 파일 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    uploadRawFile: {
        parameters: {
            query?: never;
            header?: {
                /** @description 디바이스 식별자 */
                "x-device-id"?: string;
                /** @description 충돌 감지용 클라이언트 해시 */
                "x-base-hash"?: string;
            };
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                /** @description 파일 경로 (와일드카드) */
                filePath: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/markdown": string;
            };
        };
        responses: {
            /** @description 업로드 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description 충돌 감지 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictResult"];
                };
            };
            /** @description 본문 크기 초과 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: {
                "x-device-id"?: string;
            };
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUploadRequest"];
            };
        };
        responses: {
            /** @description 업로드 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 충돌 감지 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictResult"];
                };
            };
        };
    };
    getFile: {
        parameters: {
            query?: {
                /** @description 특정 해시의 버전 내용 조회 */
                base?: string;
            };
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                /** @description 파일 경로 (와일드카드) */
                filePath: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 파일 상세 정보 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"] | components["schemas"]["BaseContentResponse"];
                };
            };
            /** @description 파일 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: {
                "x-device-id"?: string;
            };
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                /** @description 파일 경로 (와일드카드) */
                filePath: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description 파일 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listFiles: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 파일 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileInfo"][];
                };
            };
        };
    };
    listVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                /** @description 파일 경로 (와일드카드) */
                filePath: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 버전 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionListResponse"];
                };
            };
            /** @description 파일 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    editFile: {
        parameters: {
            query?: never;
            header?: {
                "x-device-id"?: string;
            };
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description 편집 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 파일 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listFolder: {
        parameters: {
            query?: {
                folder?: string;
                recursive?: "true" | "false";
            };
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 폴더 구조 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderListResponse"];
                };
            };
        };
    };
    searchFiles: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                folder?: string;
            };
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검색 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                since?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 이벤트 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
        };
    };
    updateSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncStatusRequest"];
            };
        };
        responses: {
            /** @description 동기화 상태 업데이트 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    exportVault: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 볼트 파일 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
        };
    };
    getAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                /** @description 파일 경로 (와일드카드) */
                filePath: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 바이너리 파일 내용 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                    "application/pdf": string;
                    "application/octet-stream": string;
                };
            };
            /** @description 파일 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header?: {
                "x-device-id"?: string;
            };
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                /** @description 파일 경로 (와일드카드) */
                filePath: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/png": string;
                "image/jpeg": string;
                "image/gif": string;
                "image/svg+xml": string;
                "image/webp": string;
                "application/pdf": string;
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 업로드 성공 (id, path, version 반환) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        path?: string;
                        version?: number;
                    };
                };
            };
            /** @description 본문 크기 초과 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listConflicts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 충돌 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictListResponse"];
                };
            };
        };
    };
    resolveConflict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                conflict_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConflictResolveRequest"];
            };
        };
        responses: {
            /** @description 해결 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictResolveResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 충돌 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    mergeResolveConflict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                conflict_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeResolveRequest"];
            };
        };
        responses: {
            /** @description 병합 해결 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeResolveResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 충돌 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 디바이스 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
        };
    };
    removeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 제거 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Device removed */
                        message?: string;
                    };
                };
            };
        };
    };
    batchOperations: {
        parameters: {
            query?: never;
            header?: {
                "x-device-id"?: string;
            };
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description 전체 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description 부분 성공 */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
        };
    };
    moveFile: {
        parameters: {
            query?: never;
            header?: {
                "x-device-id"?: string;
            };
            path: {
                /** @description 볼트 UUID */
                id: components["parameters"]["VaultId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description 이동 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveResponse"];
                };
            };
            /** @description 원본 파일 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 대상 경로에 이미 파일 존재 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    wsSync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket 프로토콜 전환 */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
