name: Release Obsidian Plugin
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Get Version
        id: version
        run: echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Package
        run: |
          mkdir ${{ github.event.repository.name }}
          cp main.js manifest.json styles.css README.md ${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}.zip
            main.js
            manifest.json
            styles.css
          name: ${{ steps.version.outputs.tag }}
          tag_name: ${{ steps.version.outputs.tag }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
